var date=new Date()
console.log(date.toLocaleString())
console.log(date.getDay())
console.log(date.getMonth())
console.log(date.getFullYear())
date.setFullYear(2021)
date.setHours(15)
console.log(date.toLocaleString())
console.log(date.getDay())
console.log(date.getMonth())
console.log(date.getFullYear())