var foods=[]
foods.push("pizza")
foods.push("sandwich")
foods.push("snacks")
console.log(foods)
console.log("Length ="+foods.length)
var a1=foods.pop()
var a2=foods.pop()
console.log(foods)
console.log("Length ="+foods.length)
console.log(a1)
console.log(a2)
foods.push("Burger")
console.log(foods)
console.log("Length ="+foods.length)